### ISSUE TITLE
Uninstall script doesn't undo all bindings

### ISSUE THREAD

**Issue by jacksongoode** [petrstepanov/gnome-macos-remap-wayland#2]

**Comment by petrstepanov** [comment]
Thank you for reporting!

**Comment by mdupuy** [comment]
I'm experiencing this, too. For some reason, you switched alt-tab behavior to ctrl-tab (which is strange enough) but uninstalling did not switch it back to the expected alt-tab behavior. Help!

**Comment by petrstepanov** [comment]
Thank you all for reporting, just pushed the fix.
