### ISSUE TITLE
Some issues - support for aarch64

### ISSUE THREAD

**Issue by bushaev-denis** [petrstepanov/gnome-macos-remap-wayland#3]
- Control key not working anymore, as example for change tab in the browser
- Cant jump between words with opt+left/right arrows
~~- FN key is completely brokes~~ (resolved from my side, not relates to this tweak)

**Comment by bushaev-denis** [comment]
dsads

**Comment by ppdms** [comment]
can attest to control key not working on latest fedora asahi

during uninstall:
Failed to stop gnome-macos-remap.service: Unit gnome-macos-remap.service not loaded.
Failed to disable unit: Unit file gnome-macos-remap.service does not exist.

so I guess the service was never installed correctly

**Comment by ppdms** [comment]
Nevermind, I believe it is because the downloaded binary (zip file) isn't arm64

**Comment by ppdms** [comment]
Can confirm, after compiling xremap for arm64 with cargo and installing it to the right directory everything works

**Comment by petrstepanov** [comment]
Thank you all for reporting. I just tweaked the `install.sh` script to support for the `aarch64`. Cannot test since I dont have `aarch64` here but it should work.
